---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: workspace

outputs:
- name: build-output

params:
  TERM: dumb

run:
  path: workspace/ci/tasks/build-service/task.sh
